groups:
  - name: application_alerts
    rules:
      # High CPU Usage Alert
      - alert: HighCPUUsage
        expr: container_cpu_usage_seconds_total{container_name=~"frontend|nginx"} > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage detected
          description: "Container {{ $labels.container_name }} is using {{ $value | humanizePercentage }} CPU"

      # High Memory Usage Alert
      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes{container_name=~"frontend|nginx"} / container_spec_memory_limit_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage detected
          description: "Container {{ $labels.container_name }} is using {{ $value | humanizePercentage }} memory"

      # Service Down Alert
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Service is down
          description: "Service {{ $labels.job }} is down"

      # High Error Rate Alert
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High error rate detected
          description: "Error rate is {{ $value | humanizePercentage }}"

      # SSL Certificate Expiry Alert
      - alert: SSLCertificateExpiry
        expr: ssl_certificate_expiry_timestamp < time() + 86400 * 30
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: SSL certificate expiring soon
          description: "SSL certificate will expire in {{ $value | humanizeDuration }}"

      # Hospital Specific Alerts
      - alert: HighBedOccupancy
        expr: hospital_bed_occupancy_rate > 90
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: High bed occupancy rate
          description: "Hospital bed occupancy rate is {{ $value | humanizePercentage }}"

      - alert: LowDoctorAvailability
        expr: hospital_active_appointments / hospital_total_doctors > 20
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: High doctor workload
          description: "Average appointments per doctor is {{ $value | humanize }}"

      - alert: CriticalBedShortage
        expr: hospital_bed_occupancy_rate > 95
        for: 30m
        labels:
          severity: critical
        annotations:
          summary: Critical bed shortage
          description: "Hospital bed occupancy rate is {{ $value | humanizePercentage }}" 